import { useEffect, useMemo, useRef, useState } from "react";
import { invoke, convertFileSrc } from "@tauri-apps/api/core";
import { save } from "@tauri-apps/plugin-dialog";
import { Activity, ChevronDown, Download, FolderOpen, History, Library, Pause, Play, Search, Settings2, Sparkles, Square, Volume2, WandSparkles } from "lucide-react";
import type { Catalog, Character, GenerateRequest, HistoryItem } from "./types";

type View="generate"|"library"|"history"|"settings";
const bandColor:Record<string,string>={"MyGO!!!!!":"#65b9e9","Mujica":"#7357a8","Roselia":"#3658a4","Poppin":"#ff6b8b","Afterglow":"#d84a52","RAISE A SUILEN":"#28c4ad","Morfonica":"#76cddb","Pastel＊Palettes":"#70d59c","ハロー、ハッピーワールド！":"#f0ad36"};
const avatarPages:Record<string,string>={
 "户山香澄":"Toyama_Kasumi","花园多惠":"Hanazono_Tae","牛込里美":"Ushigome_Rimi","山吹沙绫":"Yamabuki_Saaya","市谷有咲":"Ichigaya_Arisa",
 "美竹兰":"Mitake_Ran","青叶摩卡":"Aoba_Moca","上原绯玛丽":"Uehara_Himari","宇田川巴":"Udagawa_Tomoe","羽泽鸫":"Hazawa_Tsugumi",
 "丸山彩":"Maruyama_Aya","冰川日菜":"Hikawa_Hina","白鹭千圣":"Shirasagi_Chisato","大和麻弥":"Yamato_Maya","若宫伊芙":"Wakamiya_Eve",
 "凑友希那":"Minato_Yukina","冰川纱夜":"Hikawa_Sayo","今井莉莎":"Imai_Lisa","宇田川亚子":"Udagawa_Ako","大魔姬亚子":"Udagawa_Ako","白金燐子":"Shirokane_Rinko",
 "弦卷心":"Tsurumaki_Kokoro","濑田薰":"Seta_Kaoru","北泽育美":"Kitazawa_Hagumi","松原花音":"Matsubara_Kanon","奥泽美咲":"Okusawa_Misaki",
 "仓田真白":"Kurata_Mashiro","桐谷透子":"Kirigaya_Touko","广町七深":"Hiromachi_Nanami","二叶筑紫":"Futaba_Tsukushi","八潮瑠唯":"Yashio_Rui",
 "和奏瑞依":"Wakana_Rei","朝日六花":"Asahi_Rokka","佐藤益木":"Satou_Masuki","鳰原令王那":"Nyubara_Reona","珠手知由":"Tamade_Chiyu",
 "高松灯":"Takamatsu_Tomori","千早爱音":"Chihaya_Anon","要乐奈":"Kaname_Raana","长崎素世":"Nagasaki_Soyo","椎名立希":"Shiina_Taki",
 "丰川祥子":"Togawa_Sakiko","梦中情祥":"Togawa_Sakiko","若叶睦":"Wakaba_Mutsumi","墨提斯":"Wakaba_Mutsumi","三角初华":"Misumi_Uika","八幡海铃":"Yahata_Umiri","祐天寺若麦":"Yuutenji_Nyamu"
};

export default function App(){
 const [view,setView]=useState<View>("generate"),[catalog,setCatalog]=useState<Catalog|null>(null),[selected,setSelected]=useState(""),[search,setSearch]=useState("");
 const [text,setText]=useState(""),[reference,setReference]=useState(""),[speed,setSpeed]=useState(1),[temperature,setTemperature]=useState(1);
 const [busy,setBusy]=useState(false),[status,setStatus]=useState("正在读取角色资料…"),[audio,setAudio]=useState(""),[history,setHistory]=useState<HistoryItem[]>([]),[error,setError]=useState("");
 useEffect(()=>{invoke<Catalog>("load_catalog").then(c=>{setCatalog(c);setSelected(c.characters[0]?.id||"");setStatus(`${c.characters.length} 个可用声线`)}).catch(e=>setStatus(String(e)))},[]);
 useEffect(()=>{if(view==="history")invoke<HistoryItem[]>("load_history").then(setHistory)},[view,audio]);
 const characters=useMemo(()=>catalog?.characters.filter(c=>(c.name+c.band+(c.variant||"")).toLowerCase().includes(search.toLowerCase()))||[],[catalog,search]);
 const current=catalog?.characters.find(c=>c.id===selected);const currentRef=current?.references.find(r=>r.path===reference);
 useEffect(()=>{if(current?.references[0])setReference(current.references[0].path)},[selected]);
 async function generate(){if(!current||!text.trim()||!reference)return;setBusy(true);setError("");setStatus(`正在加载 ${current.name} 的声线…`);try{const req:GenerateRequest={characterId:current.id,text,textLang:/[\u3040-\u30ff]/.test(text)?"ja":"zh",referencePath:reference,promptText:currentRef?.text||"",speed,temperature,seed:-1};const path=await invoke<string>("generate_voice",{request:req});setAudio(path);setStatus("生成完成")}catch(e){const detail=String(e);setError(detail);setStatus("生成失败 · 点击查看详情")}finally{setBusy(false)}}
 const titles={generate:["CHARACTER VOICE SYNTHESIS","让熟悉的声音，说出新的故事。"],library:["VOICE LIBRARY","浏览你的角色声线资料库。"],history:["GENERATION HISTORY","重听每一次灵感。"],settings:["PREFERENCES","调整你的本地工作空间。"]};
 return <div className="shell"><aside><div className="brand"><div className="logo"><WandSparkles size={20}/></div><div><b>BanG Voice</b><span>CHARACTER STUDIO · 0.2.0</span></div></div>
  <nav><Nav active={view==="generate"} onClick={()=>setView("generate")} icon={<Sparkles/>}>语音生成</Nav><Nav active={view==="library"} onClick={()=>setView("library")} icon={<Library/>}>角色资料库</Nav><Nav active={view==="history"} onClick={()=>setView("history")} icon={<History/>}>生成记录</Nav></nav>
  <button className="system" onClick={()=>error&&setError(error)}><span><i/>Local Engine</span><small title={status}>{status}</small></button><button className={`prefs ${view==="settings"?"active":""}`} onClick={()=>setView("settings")}><Settings2/>偏好设置</button>
 </aside><main><header data-tauri-drag-region><div><p>{titles[view][0]}</p><h1>{titles[view][1]}</h1></div><div className="engine"><Activity size={16}/><span>Apple Silicon · CPU</span></div></header>
 {view==="generate"&&<GenerateView {...{characters,current,selected,setSelected,search,setSearch,text,setText,reference,setReference,speed,setSpeed,temperature,setTemperature,busy,generate,audio,currentRef}}/>}
 {view==="library"&&<LibraryView characters={characters} search={search} setSearch={setSearch} open={id=>{setSelected(id);setView("generate")}}/>}
 {view==="history"&&<HistoryView items={history}/>} {view==="settings"&&<SettingsView catalog={catalog} speed={speed} setSpeed={setSpeed} temperature={temperature} setTemperature={setTemperature}/>}</main>{error&&<div className="modal-backdrop" onClick={()=>setError("")}><div className="error-modal" onClick={e=>e.stopPropagation()}><b>生成失败</b><p>{error}</p><div><button onClick={()=>navigator.clipboard.writeText(error)}>复制错误</button><button className="primary" onClick={()=>setError("")}>知道了</button></div></div></div>}</div>
}
function Nav({active,onClick,icon,children}:{active:boolean;onClick:()=>void;icon:React.ReactNode;children:React.ReactNode}){return <button className={active?"active":""} onClick={onClick}>{icon}{children}</button>}
function GenerateView(p:any){return <div className="workspace"><section className="library"><Section n="01" title="选择角色" meta={`${p.characters.length} VOICES`}/><label className="search"><Search size={16}/><input placeholder="搜索角色或乐队…" value={p.search} onChange={(e:any)=>p.setSearch(e.target.value)}/></label><div className="character-list">{p.characters.map((c:Character)=><CharacterCard key={c.id} c={c} active={c.id===p.selected} onClick={()=>p.setSelected(c.id)}/>)}</div></section>
 <section className="composer"><Section n="02" title="编写台词" meta="JAPANESE / CHINESE"/>{p.current&&<div className="selected-voice"><Avatar c={p.current}/><div><small>当前声线</small><b>{p.current.name}</b><span>{p.current.band}{p.current.variant?` · ${p.current.variant}`:""}</span></div><Volume2/></div>}
 <div className="text-box"><textarea maxLength={500} placeholder="在这里输入想让角色说的台词…" value={p.text} onChange={(e:any)=>p.setText(e.target.value)}/><span>{p.text.length} / 500</span></div>
 <label className="field"><span>参考语音</span><div className="reference-row"><div className="select"><select value={p.reference} onChange={(e:any)=>p.setReference(e.target.value)}>{p.current?.references.slice(0,120).map((r:any,i:number)=><option value={r.path} key={r.path}>{i+1}. {r.text}</option>)}</select><ChevronDown/></div><ReferencePlayer path={p.reference}/></div></label>
 <div className="controls"><Slider label="语速" value={p.speed} set={p.setSpeed} min={0.6} max={1.4} step={0.05} suffix="×"/><Slider label="情感随机度" value={p.temperature} set={p.setTemperature} min={0.1} max={1.5} step={0.1}/></div>
 <button className="generate" disabled={p.busy||!p.text.trim()||!p.current} onClick={p.generate}>{p.busy?<><Square size={18}/>正在生成</>:<><Sparkles size={18}/>生成角色语音</>}</button>{p.audio&&<AudioResult src={p.audio}/>}</section></div>}
function LibraryView({characters,search,setSearch,open}:{characters:Character[];search:string;setSearch:(v:string)=>void;open:(id:string)=>void}){return <div className="page"><div className="page-tools"><label className="search"><Search size={16}/><input placeholder="搜索角色或乐队…" value={search} onChange={e=>setSearch(e.target.value)}/></label><span>{characters.length} 个声线</span></div><div className="voice-grid">{characters.map(c=><button className="voice-card" key={c.id} onClick={()=>open(c.id)}><Avatar c={c}/><div><b>{c.name}</b><span>{c.band}{c.variant?` · ${c.variant}`:""}</span><small>{c.references.length} 条参考语音 · {c.gptWeight&&c.sovitsWeight?"模型就绪":"仅参考素材"}</small></div><Play/></button>)}</div></div>}
function HistoryView({items}:{items:HistoryItem[]}){return <div className="page"><Section n="" title="最近生成" meta={`${items.length} FILES`}/>{items.length?<div className="history-list">{items.map(i=><div className="history-item" key={i.path}><button onClick={()=>new Audio(convertFileSrc(i.path)).play()}><Play fill="currentColor"/></button><div><b>{i.name}</b><span>{new Date(i.created*1000).toLocaleString()} · {(i.size/1024).toFixed(0)} KB</span></div><audio controls src={convertFileSrc(i.path)}/><button className="download-button" title="存储为…" onClick={()=>exportAudio(i.path,i.name)}><Download/></button></div>)}</div>:<Empty icon={<History/>} text="还没有生成记录"/>}</div>}
function SettingsView({catalog,speed,setSpeed,temperature,setTemperature}:any){return <div className="page settings-page"><section><h2>默认生成参数</h2><p>这些设置会直接用于下一次语音生成。</p><Slider label="默认语速" value={speed} set={setSpeed} min={0.6} max={1.4} step={0.05} suffix="×"/><Slider label="默认情感随机度" value={temperature} set={setTemperature} min={0.1} max={1.5} step={0.1}/></section><section><h2>本地存储</h2><p>角色语音和模型始终留在这台 Mac 上。</p><PathRow label="角色语音" value={catalog?.root}/><PathRow label="推理引擎" value={catalog?.engineRoot}/></section><section><h2>推理设备</h2><div className="device-card"><Activity/><div><b>Apple Silicon · CPU</b><span>稳定兼容模式 · 本地 127.0.0.1</span></div><em>ACTIVE</em></div></section></div>}
function ReferencePlayer({path}:{path:string}){const ref=useRef<HTMLAudioElement>(null);const[playing,setPlaying]=useState(false);useEffect(()=>{setPlaying(false);ref.current?.load()},[path]);return <button className="ref-play" disabled={!path} onClick={()=>{if(!ref.current)return;if(playing)ref.current.pause();else ref.current.play();setPlaying(!playing)}}>{playing?<Pause fill="currentColor"/>:<Play fill="currentColor"/>}<span>{playing?"暂停":"试听"}</span><audio ref={ref} src={path?convertFileSrc(path):undefined} onEnded={()=>setPlaying(false)}/></button>}
function AudioResult({src}:{src:string}){return <div className="result"><button onClick={()=>document.querySelector<HTMLAudioElement>(".result audio")?.play()}><Play fill="currentColor"/></button><audio controls src={convertFileSrc(src)}/><button className="download-button" title="存储为…" onClick={()=>exportAudio(src)}><Download/></button></div>}
async function exportAudio(path:string,name?:string){const fallback=name||path.split('/').pop()?.replace(/\.wav$/,'')||'voice';const destination=await save({defaultPath:`${fallback}.wav`,filters:[{name:'WAV 音频',extensions:['wav']}]});if(destination)await invoke("export_audio",{source:path,destination})}
function CharacterCard({c,active,onClick}:{c:Character;active:boolean;onClick:()=>void}){return <button onClick={onClick} className={`character ${active?"active":""}`}><Avatar c={c}/><div><b>{c.name}</b><span>{c.band}{c.variant?` · ${c.variant}`:""}</span></div><em>{c.gptWeight&&c.sovitsWeight?"READY":"REF"}</em></button>}
function Avatar({c}:{c:Character}){const page=avatarPages[c.name];return <div className="avatar" style={{background:bandColor[c.band]||"#7d8790"}}>{page?<img src={`/avatars/${page}.png`} alt={`${c.name}头像`}/>:c.name.slice(-1)}</div>};function Section({n,title,meta}:{n:string;title:string;meta:string}){return <div className="section-title"><div>{n&&<span>{n}</span>}<h2>{title}</h2></div><em>{meta}</em></div>};function Slider({label,value,set,min,max,step,suffix=""}:any){return <label><span>{label} <b>{Number(value).toFixed(step<.1?2:1)}{suffix}</b></span><input type="range" {...{min,max,step,value}} onChange={e=>set(+e.target.value)}/></label>};function PathRow({label,value}:{label:string;value?:string}){return <div className="path-row"><FolderOpen/><div><b>{label}</b><span>{value||"正在读取…"}</span></div></div>};function Empty({icon,text}:{icon:React.ReactNode;text:string}){return <div className="empty">{icon}<p>{text}</p></div>}
